# =============================
# Adapted from:
# 	https://github.com/ashleve/lightning-hydra-template
# =============================


help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-pycache: ## Clean Python cache files
	find . | grep -E "(__pycache__|\.pyc|\.pyo$$)" | xargs rm -rf

format: ## Run pre-commit hooks
	uv run pre-commit run -a

git-sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test-full: ## Run all tests
	uv run pytest

install: ## Install dependencies from `pyproject.toml`
	uv sync

install-dev: ## Install development dependencies from `pyproject.toml`
	uv sync --dev

install-cuda: ## Install dependencies with CUDA support
	uv sync --extra cu12

install-dev-cuda: ## Install development dependencies with CUDA support
	uv sync --dev --extra cu12

remove: ## Remove installed dependecies
	rm -rf .venv uv.lock
