name: ✨ Feature Request
description: Suggest a new feature or enhancement for Linax
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like Linax to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... but...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Use Case
      description: Provide a code example of how you'd like to use this feature
      render: python
      placeholder: |
        import linax

        # Example of how the feature would be used
        model = linax.MyNewFeature(...)
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New SSM architecture
        - New layer/module
        - API improvement
        - Performance enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be useful
        - Important
        - Critical
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: Related papers, implementations in other frameworks, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I am willing to contribute to implementing this feature
          required: false
